name: E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: hopecare_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Database
        run: |
          npx prisma migrate deploy
          npx ts-node cypress/support/seed.ts
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/hopecare_test

      - name: Build Next.js app
        run: npm run build
        env:
          NODE_ENV: test

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          start: npm run start
          wait-on: 'http://localhost:3000'
          browser: chrome
          record: ${{ secrets.CYPRESS_RECORD_KEY != '' }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/hopecare_test
          NODE_ENV: test

      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-results
          path: cypress/videos/
